name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Build & Push Docker Image to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create ECR repository if it does not exist
        run: |
          aws ecr describe-repositories --repository-names mcgeorge_app || \
          aws ecr create-repository --repository-name mcgeorge_app

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
          
      - name: Build Docker image
        run: |
          docker build -t mcgeorge_app .

      - name: Set Image Version
        run: echo "IMAGE_TAG=v${{ github.run_number }}" >> $GITHUB_ENV
      
      - name: Tag Docker image
        run: |
          docker tag mcgeorge_app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/mcgeorge_app:${{ env.IMAGE_TAG }}

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/mcgeorge_app:${{ env.IMAGE_TAG }}

  deploy_via_ansible:
    name: Deploy via Ansible Controller
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - name: Set Image Version
        run: echo "IMAGE_TAG=v${{ github.run_number }}" >> $GITHUB_ENV

      - name: SSH into Ansible Controller and run playbook
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.ANSIBLE_EC2_SSH_KEY }}
          host: ${{ secrets.ANSIBLE_EC2_HOST }}
          username: ubuntu
          port: 22
          script: |
            cd /home/ubuntu/ansible-playbooks
            echo "Running Ansible playbook..."
            ansible-playbook deploy_ec2.yaml --extra-vars "image_tag=${{ env.IMAGE_TAG }}"
