name: Deploy to AWS

on:
  push:
    branches:
      - deploy_branch

jobs:
  build_and_push:
    name: Build & Push Docker Image to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy env
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env.production

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Create ECR repository if it does not exist
        run: |
          aws ecr describe-repositories --repository-names bajaj_hr_frontend_test || \
          aws ecr create-repository --repository-name bajaj_hr_frontend_test

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com
          
      - name: Build Docker image
        run: |
          docker build -t bajaj_hr_frontend_test .

      - name: Set Image Version
        run: echo "IMAGE_TAG=v${{ github.run_number }}" >> $GITHUB_ENV
      
      - name: Tag Docker image
        run: |
          docker tag bajaj_hr_frontend_test:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com/bajaj_hr_frontend_test:${{ env.IMAGE_TAG }}

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com/bajaj_hr_frontend_test:${{ env.IMAGE_TAG }}

  deploy_to_ec2:
    name: Deploy on EC2
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
  #     # - name: Set up AWS CLI
  #     #   uses: aws-actions/configure-aws-credentials@v2
  #     #   with:
  #     #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #     #     aws-region: eu-north-1

      # - name: Read Key from Repo
      #   id: key_reader
      #   run: |
      #     KEY_CONTENT=$(cat ./windows_os.pem)
      #     echo "KEY_CONTENT<<EOF" >> $GITHUB_ENV
      #     echo "$KEY_CONTENT" >> $GITHUB_ENV
      #     echo "EOF" >> $GITHUB_ENV
      - name: Set Image Version
        run: echo "IMAGE_TAG=v${{ github.run_number }}" >> $GITHUB_ENV

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          
          
          key: ${{ secrets.EC2_SSH_KEY }}
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          port: 22
          script: |
            aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com
            docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com/bajaj_hr_frontend_test:${{ env.IMAGE_TAG }}
            docker stop bajaj_hr_frontend_test || true
            docker rm bajaj_hr_frontend_test || true
            docker run -d -p 8080:8080 --name bajaj_hr_frontend_test ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com/bajaj_hr_frontend_test:${{ env.IMAGE_TAG }}

   